library overview_main_topic;

import 'package:flutter/material.dart';

Map<int, String> mathTopic = {
  0: '''What is Quantity?
    A quantity is a property of some object or collection of objects that is measurable. A quantity or amount can be compared: one quantity can be greater than, less than, or equal to another quantity. The concept of quantity is used throughout mathematics and the sciences. For example, in comparing the lengths of two unequal line segments, one would say that the quantity of length of one line segment is greater than the quantity of length of the other. When you touch a hot stove, it feels hot because it has a greater quantity of heat than your hand does. Any property which cannot be compared is not a quantity: names are not quantities, neither is the color of my shirt (blue), nor is the property of being a scientist, etc.
    A quantity is usually presented as a product of a magnitude and a unit. For example, the quantity of height of the Empire State Building is 1454 feet. It would take 1454 foot-long rulers to measure the building from the ground to its tip. For collections of objects, each object is taken to be a unit, so we describe a carton of eggs as holding a quantity of 12 eggs.
    Save  Timeline Autoplay  Speed Normal
    Video  Quiz  Course
    36K views
    The Empire State Building.
    Very tall indeed!
    Quantity in Math
    In mathematics, we usually avoid the use of units in describing quantities and generally describe them by just their magnitude or number. This is because the properties and relations that we are investigating and describing in mathematics are abstract and the units are invariant. For example, if a problem asks for the value of quantity x in the equation x + 2 = 4, that x = 2 is the same whether the numbers in the equations are representing dollars, eggs, lightyears, or percentages.
    It is important that when we are working without units that we are careful to take notice of the dimensions that are associated with each quantity. For example, we can calculate the area of a square with a side length of 2 units to be 4 units squared.
    Square with an area of 4.
    The relation between the sides and the area is independent of the units used.
    This is important because we need to understand that 4 - 2, where 4 is the quantity of area and 2 is the quantity of length is nonsense. As a general rule quantities with different dimensions cannot be compared. Comparisons include summation, subtraction, and equality. This distinguishes geometry from arithmetic in general. Geometrical quantities have dimensions, even if they lack units, while arithmetical quantities have no dimensions if they lack units.
    In addition to geometrical quantities, which describe properties of length, area, angle, and volume, arithmetical quantities describe basic properties of magnitude or number. There are also ratio quantities which are described by fractions or percentages. Ratio quantities like 2/5 or 10% describe how two quantities are related. If the quantity of students absent out of the total quantity of students in the class is 10%, then for every nine students in attendance, one student is absent.
    Other Uses for Quantity
    Quantities are used everywhere outside of pure mathematics in both everyday lives and in many sciences. You use quantities when shopping, when counting, when doing calculus, and when remembering your age. Quantities are one of the basic tools we use to think about the world.''',
  1: '''Algebra is the part of mathematics that helps represent problems or situations in the form of mathematical expressions.  In algebra, we use numbers like 2, −7, 0.068 etc., which have a definite or fixed value. In algebra we use variables like x, y, and z along with numbers.
    Variable in Algebra
    Signs used in algebra 
    Mathematical operations like multiplication (×), division (÷), addition (+), and subtraction (−) are used to form a meaningful mathematical expression.
    There are other signs and symbols that are also frequently used in algebra.
    equal to (=), not equal to (≠), less than (<), greater than (＞), less than equal to(≤), greater than equal to ( ≥).
    Signs and symbol used in algebra
    A straightforward example of an equation in algebra is x + 5 = 10.
    Algebra A Puzzle
    Algebra is all about puzzles. 
    Here is one for you. 
    ⬜+ 10 = 13
    ⬜ plus 10 is equal to 13.
    We have to find the number in this box, and what number, when added to 10, gives us 13. Simple, it’s three; we can see that 3 plus 10 equals 13. The puzzle we see here contains only numbers. 
    We can also say that x plus 10 equals 13. Find x.
    puzzle : numbers in algebra
    We use the letter in place of the box. These letters are also called variables, sometimes referred to as the unknown since their values are unknown to us.
    Related Games
    Evaluate Algebraic Expressions with One Operation Game
    Evaluate Algebraic Expressions with One Operation Game
    Evaluate Algebraic Expressions with Two Operations Game
    Evaluate Algebraic Expressions with Two Operations Game
    Form Algebraic Expressions Game
    Form Algebraic Expressions Game
    Writing the Statements in Algebraic Form.
    The total cost of 1 kg apple and 2 kg of guava is 3. If x represents the cost of 1 kg apple and y  represents the cost of 1 kg guava, then this statement is represented in the form of an algebraic expression as:
    x + 2y = 3
    If the area of the rectangle is 36 cm2. Its length is represented as l  and width is represented as b. Then this statement is represented as :
    l  × b = 36''',
  2: '''function, in mathematics, an expression, rule, or law that defines a relationship between one variable (the independent variable) and another variable (the dependent variable). Functions are ubiquitous in mathematics and are essential for formulating physical relationships in the sciences. The modern definition of function was first given in 1837 by the German mathematician Peter Dirichlet:
    If a variable y is so related to a variable x that whenever a numerical value is assigned to x, there is a rule according to which a unique value of y is determined, then y is said to be a function of the independent variable x.
    This relationship is commonly symbolized as y = f(x)—which is said “f of x”—and y and x are related such that for every x, there is a unique value of y. That is, f(x) can not have more than one value for the same x. To use the language of set theory, a function relates an element x to an element f(x) in another set. The set of values of x is called the domain of the function, and the set of values of f(x) generated by the values in the domain is called the range of the function. In addition to f(x), other abbreviated symbols such as g(x) and P(x) are often used to represent functions of the independent variable x, especially when the nature of the function is unknown or unspecified.
    Common functions
    Many widely used mathematical formulas are expressions of known functions. For example, the formula for the area of a circle, A = πr2, gives the dependent variable A (the area) as a function of the independent variable r (the radius). Functions involving more than two variables (called multivariable or multivariate functions) also are common in mathematics, as can be seen in the formula for the area of a triangle, A = bh/2, which defines A as a function of both b (base) and h (height). In these examples, physical constraints force the independent variables to be positive numbers. When the independent variables are also allowed to take on negative values—thus, any real number—the functions are known as real-valued functions.
    The formula for the area of a circle is an example of a polynomial function. The general form for such functions is
    P(x) = a0 + a1x + a2x2+⋯+ anxn,
    where the coefficients (a0, a1, a2,…, an) are given, x can be any real number, and all the powers of x are counting numbers (1, 2, 3,…). (When the powers of x can be any real number, the result is known as an algebraic function.) Polynomial functions have been studied since the earliest times because of their versatility—practically any relationship involving real numbers can be closely approximated by a polynomial function. Polynomial functions are characterized by the highest power of the independent variable. Special names are commonly used for such powers from one to five—linear, quadratic, cubic, quartic, and quintic for the highest powers being 1, 2, 3, 4, and 5, respectively.
    Polynomial functions may be given geometric representation by means of analytic geometry. The independent variable x is plotted along the x-axis (a horizontal line), and the dependent variable y is plotted along the y-axis (a vertical line). When the graph of a relation between x and y is plotted in the x-y plane, the relation is a function if a vertical line always passes through only one point of the graphed curve; that is, there would be only one point f(x) corresponding to each x, which is the definition of a function. The graph of the function then consists of the points with coordinates (x, y) where y = f(x). For example, the graph of the cubic equation f(x) = x3 − 3x + 2 is shown in the figure.
    Another common type of function that has been studied since antiquity is the trigonometric functions, such as sin x and cos x, where x is the measure of an angle (see figure). Because of their periodic nature, trigonometric functions are often used to model behaviour that repeats, or “cycles.”''',
  3: '''A mathematical model is an abstract description of a concrete system using mathematical concepts and language. The process of developing a mathematical model is termed mathematical modeling. Mathematical models are used in applied mathematics and in the natural sciences (such as physics, biology, earth science, chemistry) and engineering disciplines (such as computer science, electrical engineering), as well as in non-physical systems such as the social sciences[1] (such as economics, psychology, sociology, political science). It can also be taught as a subject in its own right.[2]
    The use of mathematical models to solve problems in business or military operations is a large part of the field of operations research.
    Mathematical models are also used in music,[3] linguistics,[4] and philosophy (for example, intensively in analytic philosophy).
    A model may help to explain a system and to study the effects of different components, and to make predictions about behavior.
    Elements of a mathematical model
    Mathematical models can take many forms, including dynamical systems, statistical models, differential equations, or game theoretic models. These and other types of models can overlap, with a given model involving a variety of abstract structures. In general, mathematical models may include logical models. In many cases, the quality of a scientific field depends on how well the mathematical models developed on the theoretical side agree with results of repeatable experiments. Lack of agreement between theoretical mathematical models and experimental measurements often leads to important advances as better theories are developed.
    In the physical sciences, a traditional mathematical model contains most of the following elements:
    Governing equations
    Supplementary sub-models
    Defining equations
    Constitutive equations
    Assumptions and constraints
    Initial and boundary conditions
    Classical constraints and kinematic equations
    Classifications
    Mathematical models are of different types:
    Linear vs. nonlinear: If all the operators in a mathematical model exhibit linearity, the resulting mathematical model is defined as linear. A model is considered to be nonlinear otherwise. The definition of linearity and nonlinearity is dependent on context, and linear models may have nonlinear expressions in them. For example, in a statistical linear model, it is assumed that a relationship is linear in the parameters, but it may be nonlinear in the predictor variables. Similarly, a differential equation is said to be linear if it can be written with linear differential operators, but it can still have nonlinear expressions in it. In a mathematical programming model, if the objective functions and constraints are represented entirely by linear equations, then the model is regarded as a linear model. If one or more of the objective functions or constraints are represented with a nonlinear equation, then the model is known as a nonlinear model.
    Linear structure implies that a problem can be decomposed into simpler parts that can be treated independently and/or analyzed at a different scale and the results obtained will remain valid for the initial problem when recomposed and rescaled.
    Nonlinearity, even in fairly simple systems, is often associated with phenomena such as chaos and irreversibility. Although there are exceptions, nonlinear systems and models tend to be more difficult to study than linear ones. A common approach to nonlinear problems is linearization, but this can be problematic if one is trying to study aspects such as irreversibility, which are strongly tied to nonlinearity.
    Static vs. dynamic: A dynamic model accounts for time-dependent changes in the state of the system, while a static (or steady-state) model calculates the system in equilibrium, and thus is time-invariant. Dynamic models typically are represented by differential equations or difference equations.
    Explicit vs. implicit: If all of the input parameters of the overall model are known, and the output parameters can be calculated by a finite series of computations, the model is said to be explicit. But sometimes it is the output parameters which are known, and the corresponding inputs must be solved for by an iterative procedure, such as Newton's method or Broyden's method. In such a case the model is said to be implicit. For example, a jet engine's physical properties such as turbine and nozzle throat areas can be explicitly calculated given a design thermodynamic cycle (air and fuel flow rates, pressures, and temperatures) at a specific flight condition and power setting, but the engine's operating cycles at other flight conditions and power settings cannot be explicitly calculated from the constant physical properties.
    Discrete vs. continuous: A discrete model treats objects as discrete, such as the particles in a molecular model or the states in a statistical model; while a continuous model represents the objects in a continuous manner, such as the velocity field of fluid in pipe flows, temperatures and stresses in a solid, and electric field that applies continuously over the entire model due to a point charge.
    Deterministic vs. probabilistic (stochastic): A deterministic model is one in which every set of variable states is uniquely determined by parameters in the model and by sets of previous states of these variables; therefore, a deterministic model always performs the same way for a given set of initial conditions. Conversely, in a stochastic model—usually called a "statistical model"—randomness is present, and variable states are not described by unique values, but rather by probability distributions.
    Deductive, inductive, or floating: A deductive model is a logical structure based on a theory. An inductive model arises from empirical findings and generalization from them. The floating model rests on neither theory nor observation, but is merely the invocation of expected structure. Application of mathematics in social sciences outside of economics has been criticized for unfounded models.[5] Application of catastrophe theory in science has been characterized as a floating model.[6]
    Strategic vs non-strategic Models used in game theory are different in a sense that they model agents with incompatible incentives, such as competing species or bidders in an auction. Strategic models assume that players are autonomous decision makers who rationally choose actions that maximize their objective function. A key challenge of using strategic models is defining and computing solution concepts such as Nash equilibrium. An interesting property of strategic models is that they separate reasoning about rules of the game from reasoning about behavior of the players.[7]''',
  4: '''
    Geometry (from Ancient Greek γεωμετρία (geōmetría) 'land measurement'; from γῆ (gê) 'earth, land', and μέτρον (métron) 'a measure')[citation needed] is a branch of mathematics concerned with properties of space such as the distance, shape, size, and relative position of figures.[1] Geometry is, along with arithmetic, one of the oldest branches of mathematics. A mathematician who works in the field of geometry is called a geometer. Until the 19th century, geometry was almost exclusively devoted to Euclidean geometry,[a] which includes the notions of point, line, plane, distance, angle, surface, and curve, as fundamental concepts.[2]
    Originally developed to model the physical world, geometry has applications in almost all sciences, and also in art, architecture, and other activities that are related to graphics.[3] Geometry also has applications in areas of mathematics that are apparently unrelated. For example, methods of algebraic geometry are fundamental in Wiles's proof of Fermat's Last Theorem, a problem that was stated in terms of elementary arithmetic, and remained unsolved for several centuries.
    During the 19th century several discoveries enlarged dramatically the scope of geometry. One of the oldest such discoveries is Carl Friedrich Gauss' Theorema Egregium ("remarkable theorem") that asserts roughly that the Gaussian curvature of a surface is independent from any specific embedding in a Euclidean space. This implies that surfaces can be studied intrinsically, that is, as stand-alone spaces, and has been expanded into the theory of manifolds and Riemannian geometry. Later in the 19th century, it appeared that geometries without the parallel postulate (non-Euclidean geometries) can be developed without introducing any contradiction. The geometry that underlies general relativity is a famous application of non-Euclidean geometry.
    Since the late 19th century, the scope of geometry has been greatly expanded, and the field has been split in many subfields that depend on the underlying methods—differential geometry, algebraic geometry, computational geometry, algebraic topology, discrete geometry (also known as combinatorial geometry), etc.—or on the properties of Euclidean spaces that are disregarded—projective geometry that consider only alignment of points but not distance and parallelism, affine geometry that omits the concept of angle and distance, finite geometry that omits continuity, and others. This enlargement of the scope of geometry led to a change of meaning of the word "space", which originally referred to the three-dimensional space of the physical world and its model provided by Euclidean geometry; presently a geometric space, or simply a space is a mathematical structure on which some geometry is defined.
      ''',
  5: '''
    Statistics (from German: Statistik, orig. "description of a state, a country")[1][2] is the discipline that concerns the collection, organization, analysis, interpretation, and presentation of data.[3][4][5] In applying statistics to a scientific, industrial, or social problem, it is conventional to begin with a statistical population or a statistical model to be studied. Populations can be diverse groups of people or objects such as "all people living in a country" or "every atom composing a crystal". Statistics deals with every aspect of data, including the planning of data collection in terms of the design of surveys and experiments.[6]
    When census data cannot be collected, statisticians collect data by developing specific experiment designs and survey samples. Representative sampling assures that inferences and conclusions can reasonably extend from the sample to the population as a whole. An experimental study involves taking measurements of the system under study, manipulating the system, and then taking additional measurements using the same procedure to determine if the manipulation has modified the values of the measurements. In contrast, an observational study does not involve experimental manipulation.
    Two main statistical methods are used in data analysis: descriptive statistics, which summarize data from a sample using indexes such as the mean or standard deviation, and inferential statistics, which draw conclusions from data that are subject to random variation (e.g., observational errors, sampling variation).[7] Descriptive statistics are most often concerned with two sets of properties of a distribution (sample or population): central tendency (or location) seeks to characterize the distribution's central or typical value, while dispersion (or variability) characterizes the extent to which members of the distribution depart from its center and each other. Inferences on mathematical statistics are made under the framework of probability theory, which deals with the analysis of random phenomena.
    A standard statistical procedure involves the collection of data leading to a test of the relationship between two statistical data sets, or a data set and synthetic data drawn from an idealized model. A hypothesis is proposed for the statistical relationship between the two data sets, and this is compared as an alternative to an idealized null hypothesis of no relationship between two data sets. Rejecting or disproving the null hypothesis is done using statistical tests that quantify the sense in which the null can be proven false, given the data that are used in the test. Working from a null hypothesis, two basic forms of error are recognized: Type I errors (null hypothesis is falsely rejected giving a "false positive") and Type II errors (null hypothesis fails to be rejected and an actual relationship between populations is missed giving a "false negative").[8] Multiple problems have come to be associated with this framework, ranging from obtaining a sufficient sample size to specifying an adequate null hypothesis.[7]
    Statistical measurement processes are also prone to error in regards to the data that they generate. Many of these errors are classified as random (noise) or systematic (bias), but other types of errors (e.g., blunder, such as when an analyst reports incorrect units) can also occur. The presence of missing data or censoring may result in biased estimates and specific techniques have been developed to address these problems.
    Introduction
    Main article: Outline of statistics
    Statistics is a mathematical body of science that pertains to the collection, analysis, interpretation or explanation, and presentation of data,[9] or as a branch of mathematics.[10] Some consider statistics to be a distinct mathematical science rather than a branch of mathematics. While many scientific investigations make use of data, statistics is concerned with the use of data in the context of uncertainty and decision-making in the face of uncertainty.[11][12]
    In applying statistics to a problem, it is common practice to start with a population or process to be studied. Populations can be diverse topics, such as "all people living in a country" or "every atom composing a crystal". Ideally, statisticians compile data about the entire population (an operation called a census). This may be organized by governmental statistical institutes. Descriptive statistics can be used to summarize the population data. Numerical descriptors include mean and standard deviation for continuous data (like income), while frequency and percentage are more useful in terms of describing categorical data (like education).
    When a census is not feasible, a chosen subset of the population called a sample is studied. Once a sample that is representative of the population is determined, data is collected for the sample members in an observational or experimental setting. Again, descriptive statistics can be used to summarize the sample data. However, drawing the sample contains an element of randomness; hence, the numerical descriptors from the sample are also prone to uncertainty. To draw meaningful conclusions about the entire population, inferential statistics are needed. It uses patterns in the sample data to draw inferences about the population represented while accounting for randomness. These inferences may take the form of answering yes/no questions about the data (hypothesis testing), estimating numerical characteristics of the data (estimation), describing associations within the data (correlation), and modeling relationships within the data (for example, using regression analysis). Inference can extend to the forecasting, prediction, and estimation of unobserved values either in or associated with the population being studied. It can include extrapolation and interpolation of time series or spatial data, as well as data mining.
    '''
  
};
